[package]
name = "sepax2d"
license = "MIT OR Apache-2.0"
description = "A safe crate for finding and resolving collisions of 2D convex polygons using the Separating Axis Theorem."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/meowitzher/sepax2d/"

[dependencies]